---
- hosts: funnier
  user: vagrant
  strategy: free
  sudo: yes
  tasks:
    - name: Install Nginx
      apt: pkg=nginx state=installed update_cache=true
      notify: Start Nginx
    - name: Install Python 3
      apt: pkg=python3-minimal state=installed

  handlers:
    - name: Start Nginx
      service: name=nginx state=started
